version: 1.0.1
shapekeys:
  - browDownLeft
  - browDownRight
  - browInnerUp
  - browOuterUpLeft
  - browOuterUpRight
  - cheekPuff
  - cheekSquintLeft
  - cheekSquintRight
  - eyeBlinkLeft
  - eyeBlinkRight
  - eyeLookDownLeft
  - eyeLookDownRight
  - eyeLookInLeft
  - eyeLookInRight
  - eyeLookOutLeft
  - eyeLookOutRight
  - eyeLookUpLeft
  - eyeLookUpRight
  - eyeSquintLeft
  - eyeSquintRight
  - eyeWideLeft
  - eyeWideRight
  - jawForward
  - jawLeft
  - jawOpen
  - jawRight
  - mouthClose
  - mouthDimpleLeft
  - mouthDimpleRight
  - mouthFrownLeft
  - mouthFrownRight
  - mouthFunnel
  - mouthLeft
  - mouthLowerDownLeft
  - mouthLowerDownRight
  - mouthPressLeft
  - mouthPressRight
  - mouthPucker
  - mouthRight
  - mouthRollLower
  - mouthRollUpper
  - mouthShrugLower
  - mouthShrugUpper
  - mouthSmileLeft
  - mouthSmileRight
  - mouthStretchLeft
  - mouthStretchRight
  - mouthUpperUpLeft
  - mouthUpperUpRight
  - noseSneerLeft
  - noseSneerRight
  - tongueOut
  - viseme_sil
  - viseme_PP
  - viseme_FF
  - viseme_TH
  - viseme_DD
  - viseme_kk
  - viseme_CH
  - viseme_SS
  - viseme_nn
  - viseme_RR
  - viseme_aa
  - viseme_E
  - viseme_I
  - viseme_O
  - viseme_U
  - NEUTRAL
  - A
  - I
  - U
  - E
  - O
  - Blink
  - Blink_R
  - Blink_L
  - JOY
  - ANGRY
  - SORROW
  - FUN
  - LOOKUP
  - LOOKDOWN
  - LOOKLEFT
  - LOOKRIGHT
  - pupil_smaller
  - pupil_bigger
  - mouthRotate_L
  - mouthRotate_R
  - halfmoonEye
  - brow_innerRotate_L
  - brow_innerRotate_R
  - brow_innerUp_L
  - brow_innerUp_R
  - brow_middle01Up_L
  - brow_middle01Up_R
  - brow_middle02Up_L
  - brow_middle02Up_R
  - brow_middle03Up_L
  - brow_middle03Up_R
  - brow_endUp_L
  - brow_endUp_R
  - brow_innerDown_L
  - brow_innerDown_R
  - brow_middle01Down_L
  - brow_middle01Down_R
  - brow_middle02Down_L
  - brow_middle02Down_R
  - brow_middle03Down_L
  - brow_middle03Down_R
  - brow_endDown_L
  - brow_endDown_R
shapekeys_mouth:
  - jawForward
  - jawLeft
  - jawOpen
  - jawRight
  - mouthClose
  - mouthDimpleLeft
  - mouthDimpleRight
  - mouthFrownLeft
  - mouthFrownRight
  - mouthFunnel
  - mouthLeft
  - mouthLowerDownLeft
  - mouthLowerDownRight
  - mouthPressLeft
  - mouthPressRight
  - mouthPucker
  - mouthRight
  - mouthRollLower
  - mouthRollUpper
  - mouthShrugLower
  - mouthShrugUpper
  - mouthSmileLeft
  - mouthSmileRight
  - mouthStretchLeft
  - mouthStretchRight
  - mouthUpperUpLeft
  - mouthUpperUpRight
  - noseSneerLeft
  - noseSneerRight
  - tongueOut
  - viseme_sil
  - viseme_PP
  - viseme_FF
  - viseme_TH
  - viseme_DD
  - viseme_kk
  - viseme_CH
  - viseme_SS
  - viseme_nn
  - viseme_RR
  - viseme_aa
  - viseme_E
  - viseme_I
  - viseme_O
  - viseme_U
  - NEUTRAL
  - A
  - I
  - U
  - E
  - O
  - JOY
  - ANGRY
  - SORROW
  - FUN
  - mouthRotate_L
  - mouthRotate_R
parts_categories:
  - Head_Face
  - Head_Ears
  - Head_Brows
  - Head_Eyes
  - Head_Teeth
  - Head_Nose
  - Body_Full
  - Prop_Hood
  - Prop_Helmet
  - Prop_Hair
  - Prop_Headwear
  - Prop_Eyewear
  - Prop_Facewear
  - Prop_FacialJewelry
  - Prop_Accessory
  - Prop_Hand
  - Prop_Bag
  - Prop_Back
  - Prop_Decoration
  - Prop_Socks
  - Prop_Footwear
  - Prop_Dress
  - Prop_Top
  - Prop_Bottom
  - Prop_Outwear
  - Prop_SpecialBodysuit
shapekey_categories:
  - Head_Face
  - Head_Ears
  - Head_Brows
  - Head_Eyes
  - Head_Teeth
  - Prop_Facewear
  - Prop_FacialJewelry
mandatory_head_categories:
  - Head_Face
mandatory_parts_categories:
  - Head_Face
  - Body_Full
bones:
  - Hips
  - Spine
  - Spine1
  - Spine2
  - Neck
  - Head
  - HeadTop_End
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  - RightHandThumb1
  - RightHandThumb2
  - RightHandThumb3
  - RightHandThumb4
  - RightHandIndex1
  - RightHandIndex2
  - RightHandIndex3
  - RightHandIndex4
  - RightHandMiddle1
  - RightHandMiddle2
  - RightHandMiddle3
  - RightHandMiddle4
  - RightHandRing1
  - RightHandRing2
  - RightHandRing3
  - RightHandRing4
  - RightHandPinky1
  - RightHandPinky2
  - RightHandPinky3
  - RightHandPinky4
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - LeftHandThumb1
  - LeftHandThumb2
  - LeftHandThumb3
  - LeftHandThumb4
  - LeftHandIndex1
  - LeftHandIndex2
  - LeftHandIndex3
  - LeftHandIndex4
  - LeftHandMiddle1
  - LeftHandMiddle2
  - LeftHandMiddle3
  - LeftHandMiddle4
  - LeftHandRing1
  - LeftHandRing2
  - LeftHandRing3
  - LeftHandRing4
  - LeftHandPinky1
  - LeftHandPinky2
  - LeftHandPinky3
  - LeftHandPinky4
  - RightUpLeg
  - RightLeg
  - RightFoot
  - RightToeBase
  - RightToe_End
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - LeftToeBase
  - LeftToe_End
shapekey_blockers:
  mouth:
    category:
    parts:
