version: 1.0.1
shapekeys:
  - browDownLeft
  - browDownRight
  - browInnerUp
  - browOuterUpLeft
  - browOuterUpRight
  - cheekPuff
  - cheekSquintLeft
  - cheekSquintRight
  - eyeBlinkLeft
  - eyeBlinkRight
  - eyeLookDownLeft
  - eyeLookDownRight
  - eyeLookInLeft
  - eyeLookInRight
  - eyeLookOutLeft
  - eyeLookOutRight
  - eyeLookUpLeft
  - eyeLookUpRight
  - eyeSquintLeft
  - eyeSquintRight
  - eyeWideLeft
  - eyeWideRight
  - jawForward
  - jawLeft
  - jawOpen
  - jawRight
  - mouthClose
  - mouthDimpleLeft
  - mouthDimpleRight
  - mouthFrownLeft
  - mouthFrownRight
  - mouthFunnel
  - mouthLeft
  - mouthLowerDownLeft
  - mouthLowerDownRight
  - mouthPressLeft
  - mouthPressRight
  - mouthPucker
  - mouthRight
  - mouthRollLower
  - mouthRollUpper
  - mouthShrugLower
  - mouthShrugUpper
  - mouthSmileLeft
  - mouthSmileRight
  - mouthStretchLeft
  - mouthStretchRight
  - mouthUpperUpLeft
  - mouthUpperUpRight
  - noseSneerLeft
  - noseSneerRight
  - tongueOut
  - viseme_sil
  - viseme_PP
  - viseme_FF
  - viseme_TH
  - viseme_DD
  - viseme_kk
  - viseme_CH
  - viseme_SS
  - viseme_nn
  - viseme_RR
  - viseme_aa
  - viseme_E
  - viseme_I
  - viseme_O
  - viseme_U
  - NEUTRAL
  - A
  - I
  - U
  - E
  - O
  - Blink
  - Blink_R
  - Blink_L
  - JOY
  - ANGRY
  - SORROW
  - FUN
  - LOOKUP
  - LOOKDOWN
  - LOOKLEFT
  - LOOKRIGHT
  - pupil_smaller
  - pupil_bigger
  - mouthRotate_L
  - mouthRotate_R
  - halfmoonEye
  - brow_innerRotate_L
  - brow_innerRotate_R
  - brow_innerUp_L
  - brow_innerUp_R
  - brow_middle01Up_L
  - brow_middle01Up_R
  - brow_middle02Up_L
  - brow_middle02Up_R
  - brow_middle03Up_L
  - brow_middle03Up_R
  - brow_endUp_L
  - brow_endUp_R
  - brow_innerDown_L
  - brow_innerDown_R
  - brow_middle01Down_L
  - brow_middle01Down_R
  - brow_middle02Down_L
  - brow_middle02Down_R
  - brow_middle03Down_L
  - brow_middle03Down_R
  - brow_endDown_L
  - brow_endDown_R
parts_categories:
  - Type
  - Eyebrow
  - Eyes
  - Teeth
  - Hair
  - Hat
  - Helmet
  - Eyewear
  - MouthProp
  - Jewelry
  - Clothing
  - Accessory
  - Bag
  - BackAttachment
  - Bottom
  - Shoes
  - BG
shapekey_categories:
  - Type
  - Eyebrow
  - Eyes
  - Teeth
mandatory_head_categories:
  - Type
mandatory_parts_categories:
  - Type
bones:
  - mixamorig:Hips
  - mixamorig:Spine
  - mixamorig:Spine1
  - mixamorig:Spine2
  - mixamorig:Neck
  - mixamorig:Head
  - mixamorig:HeadTop_End
  - mixamorig:RightShoulder
  - mixamorig:RightArm
  - mixamorig:RightForeArm
  - mixamorig:RightHand
  - mixamorig:RightHandThumb1
  - mixamorig:RightHandThumb2
  - mixamorig:RightHandThumb3
  - mixamorig:RightHandThumb4
  - mixamorig:RightHandIndex1
  - mixamorig:RightHandIndex2
  - mixamorig:RightHandIndex3
  - mixamorig:RightHandIndex4
  - mixamorig:RightHandMiddle1
  - mixamorig:RightHandMiddle2
  - mixamorig:RightHandMiddle3
  - mixamorig:RightHandMiddle4
  - mixamorig:RightHandRing1
  - mixamorig:RightHandRing2
  - mixamorig:RightHandRing3
  - mixamorig:RightHandRing4
  - mixamorig:RightHandPinky1
  - mixamorig:RightHandPinky2
  - mixamorig:RightHandPinky3
  - mixamorig:RightHandPinky4
  - mixamorig:LeftShoulder
  - mixamorig:LeftArm
  - mixamorig:LeftForeArm
  - mixamorig:LeftHand
  - mixamorig:LeftHandThumb1
  - mixamorig:LeftHandThumb2
  - mixamorig:LeftHandThumb3
  - mixamorig:LeftHandThumb4
  - mixamorig:LeftHandIndex1
  - mixamorig:LeftHandIndex2
  - mixamorig:LeftHandIndex3
  - mixamorig:LeftHandIndex4
  - mixamorig:LeftHandMiddle1
  - mixamorig:LeftHandMiddle2
  - mixamorig:LeftHandMiddle3
  - mixamorig:LeftHandMiddle4
  - mixamorig:LeftHandRing1
  - mixamorig:LeftHandRing2
  - mixamorig:LeftHandRing3
  - mixamorig:LeftHandRing4
  - mixamorig:LeftHandPinky1
  - mixamorig:LeftHandPinky2
  - mixamorig:LeftHandPinky3
  - mixamorig:LeftHandPinky4
  - mixamorig:RightUpLeg
  - mixamorig:RightLeg
  - mixamorig:RightFoot
  - mixamorig:RightToeBase
  - mixamorig:RightToe_End
  - mixamorig:LeftUpLeg
  - mixamorig:LeftLeg
  - mixamorig:LeftFoot
  - mixamorig:LeftToeBase
  - mixamorig:LeftToe_End
